name: Discord Notify

on:
  push:
    branches:
      - main   # Only trigger on pushes to main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send commit info to Discord
        uses: rjstone/discord-webhook-notify@v2
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          username: GitHub
          title: "Push to Main"
          text: |
            **Repository:** ${{ github.repository }}
            **Branch:** ${{ github.ref }}
            **Pusher:** ${{ github.actor }}

            **Commit Message:** ${{ github.event.head_commit.message }}
            **Author:** ${{ github.event.head_commit.author.name }}
            **Commit:** [${{ github.sha }}](${{ github.event.head_commit.url }})
