name: Discord Notify

on:
  push:
    branches:
      - main   # Only trigger on pushes to main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send commit info to Discord
        uses: rjstone/discord-webhook-notify@v2
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          username: GitHub
          title: "Push to Main"
          text: |
            **Push to Main**
            ${{ github.sha }}