name: Discord Notify

on:
  push:
    branches:
      - main   # Only trigger on pushes to main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send commit info to Discord
        env: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          repo="${GITHUB_REPOSITORY}"
          commits=$(jq -r --arg repo "$repo" '.commits[] | "- [" + .message + "](" + .url + ") (by " + .author.name + ")"' $GITHUB_EVENT_PATH | tr '\n' '\n')
          payload=$(jq -n --arg content "🚀 Push to **main** by $GITHUB_ACTOR:\n$commits" '{content: $content}')
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "$payload"
