name: Discord Notify

on:
  push:
    branches:
      - main   # Only trigger on pushes to main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send custom embed to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_REPO: ${{ github.repository }}
          COMMIT_URL: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
          AVATAR_URL: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          COMMIT_MSG: ${{ github.event.head_commit.message }}
          COMMIT_TIMESTAMP: ${{ github.event.head_commit.timestamp }}
        run: |
          jq -n --arg username "GitHub" \
                --arg avatar_url "$AVATAR_URL" \
                --arg title "${GITHUB_ACTOR} pushed to main" \
                --arg url "$COMMIT_URL" \
                --arg description "$COMMIT_MSG" \
                --arg author_name "$GITHUB_ACTOR" \
                --arg author_url "https://github.com/$GITHUB_ACTOR" \
                --arg repo_name "$GITHUB_REPO" \
                --arg repo_url "https://github.com/$GITHUB_REPO" \
                --arg commit_sha "$GITHUB_SHA" \
                --arg commit_url "$COMMIT_URL" \
                --arg timestamp "$COMMIT_TIMESTAMP" \
                '{
                  username: $username,
                  avatar_url: $avatar_url,
                  embeds: [
                    {
                      title: $title,
                      url: $url,
                      description: $description,
                      color: 2368548,
                      author: {
                        name: $author_name,
                        url: $author_url
                      },
                      fields: [
                        {
                          name: "Repository",
                          value: "[" + $repo_name + "](" + $repo_url + ")",
                          inline: true
                        },
                        {
                          name: "Commit",
                          value: "[`" + $commit_sha + "`](" + $commit_url + ")",
                          inline: true
                        }
                      ],
                      timestamp: $timestamp
                    }
                  ]
                }' > discord-embed.json

          curl -H "Content-Type: application/json" -X POST \
            -d @discord-embed.json \
            $DISCORD_WEBHOOK